FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8-slim
RUN pip install --no-cache-dir tensorflow==2.9.1 numpy==1.23.1 pydantic==1.9.1 sentence-transformers==2.2.2
COPY main.py ./main.py
COPY ./all-mpnet-base-v2 /all-mpnet-base-v2